# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

dart_code_metrics:
  metrics:
    lines-for-function: 50
    lines-for-file: 300
  metrics-exclude:
    - test/**

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"

# Dart formatting options
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  # Line length for Dart formatter
  # This sets the preferred line length for the Dart formatter to 120 characters
  # IDEs like IntelliJ IDEA use this setting for code formatting

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
